### ISSUE TITLE
Don't ship CHANGELOG with wheels

### ISSUE THREAD

**Issue by akx** [sco1/flake8-annotations#117]
**Describe the bug**

Upon uninstalling the package (temporarily, don't worry! 😁 ), I noticed it had dropped a `CHANGELOG.md` in `site-packages`. It probably shouldn't.

```
$ pip uninstall flake8-annotations
Found existing installation: flake8-annotations 2.6.2
Uninstalling flake8-annotations-2.6.2:
  Would remove:
    .../lib/python3.9/site-packages/CHANGELOG.md
    .../lib/python3.9/site-packages/flake8_annotations-2.6.2.dist-info/*
    .../lib/python3.9/site-packages/flake8_annotations/*
```

**To Reproduce**

Minimal code example to reproduce the behavior:

* install `flake8-annotations`
* look in your site-packages

**Version Information**

* flake8-annotations 2.6.2
* Python 3.9
* pip 20.3.1

**Comment by sco1** [comment]
Interesting! Never noticed this. I guess I've never uninstalled 😄

I think this was just copied from [Poetry's documentation](https://python-poetry.org/docs/pyproject/#include-and-exclude) when this was moved from pipenv. I'll change it now so future releases won't do this.

Thanks!
