### ISSUE TITLE
It seems that flake8 plugin is not active

### ISSUE THREAD

**Issue by okvdeveritec** [sco1/flake8-annotations#127]
**Describe the bug**
I have a code which is missing type annotations. I have installed flake8 and flake8-annotations to my virtual env, but when I am running:
```bash
$ python3 -m flake8 .
```
I am not getting any warnings. Maybe it worth to mention that pycodestyle does not work as well...

**To Reproduce**
Minimal code example to reproduce the behavior:

```py
def main():
    return

def fun(a, b):
    return a + b
```

**Version Information**
```bash
$ flake8 --version
3.9.1 (flake8-annotations: 2.7.0, mccabe: 0.6.1, pycodestyle: 2.7.0, pyflakes: 2.3.1) CPython 3.8.12 on Linux
```

As well as your Python version:
```bash
$ python -V
Python 3.8.12
```

**Comment by sco1** [comment]
I'm not able to reproduce on my end:

```bash
(.venv) $ python -V
Python 3.8.12

(.venv) $ python -m flake8 --version
4.0.1 (flake8-annotations: 2.7.0, mccabe: 0.6.1, pycodestyle: 2.8.0, pyflakes: 2.4.0) CPython 3.8.12 on Darwin

(.venv) $ cat ./asdf.py
def main():
    return

def fun(a, b):
    return a + b

(.venv) $ python -m flake8 ./asdf.py
./asdf.py:1:11: ANN201 Missing return type annotation for public function
./asdf.py:4:1: E302 expected 2 blank lines, found 1
./asdf.py:4:9: ANN001 Missing type annotation for function argument 'a'
./asdf.py:4:12: ANN001 Missing type annotation for function argument 'b'
./asdf.py:4:14: ANN201 Missing return type annotation for public function
```

I see a few different ways you're invoking `python` and `flake8`, can you confirm that they are all pointing to the correct interpreter?

If that's not the issue, what does flake8's verbose output (`flake8 -v`) look like?

**Comment by okvdeveritec** [comment]
Your question about flake config file was very helpful. Problem was there!
The line ```select = B,C,E,F,W,T4,B9``` was limiting flake8 output. Thank you for your fast response.
