### ISSUE TITLE
Add ANN200 error for "Function returns Any"

### ISSUE THREAD

**Issue by silasary** [sco1/flake8-annotations#131]
**Description**
Marking a function as `-> Any` is effectively the same as not having an annotation at all.  There should be an error reporting such annotations.

**Comment by sco1** [comment]
I think a case can be made to add an opinonated. off by default, warning (a la mypy's [dynamic typing options](https://mypy.readthedocs.io/en/stable/command_line.html#disallow-dynamic-typing)). I'm not sure there's a reason to limit it to just return annotations.
