### ISSUE TITLE
400 level errors on by default

### ISSUE THREAD

**Issue by agbaum** [sco1/flake8-annotations#134]
**Describe the bug**

We just upgraded to 2.8.0 and have a bunch of litning errors stemming from code using the `Any` annotation. It looks like from the docs that those errors are intended to be off by default, but it's unclear from the docs how one would turn them on, and so I can't figure out if there's something we've done to turn them on, or if they're just actually on by default.

Is this a bug, or do we need to just disable this error?

**Version Information**
Please provide the full output of `flake8 --version`

```bash
$ flake8 --version
4.0.0 (flake8-annotations: 2.8.0, flake8-bandit: 3.0.0, flake8-docstrings:
1.6.0, pydocstyle: 6.1.1, flake8_isort: 4.1.1, mccabe: 0.6.1, pycodestyle:
2.8.0, pyflakes: 2.4.0) CPython 3.7.12 on Linux
```

As well as your Python version:
```bash
$ python -V
Python 3.7.12

```

**Comment by agbaum** [comment]
ahhh we were using `ignore`. I'll switch us over to `extend-ignore`. Thanks for the speedy response!

**Comment by sziem** [comment]
I've been wondering for quite a while, why I sometimes (but now always) get `ANN401`, although it is supposed to be off by default and just stumbled across this.  

It makes a lot of sense, but as a small suggestion, maybe you could add to the docs that the `ignore` config key is the mechanism by which 400 levels are ignored and add this info on `ignore` vs `extend-ignore`.

Thanks for your work!

**Comment by sco1** [comment]
Sure, I can add a note.
