### ISSUE TITLE
Exclude `*args` and `**kwargs` from ANN401

### ISSUE THREAD

**Issue by jpy-git** [sco1/flake8-annotations#135]
**Describe the bug**
I like the new ANN401 rule added in the v2.8.0 release.

However, one place where it's pretty common to use `Any` is in annotations for `*args` and `**kwargs` since they often (not always) can take mulitple types.

**To Reproduce**

```py
def foo(*args: Any, **kwargs: Any): ...
```
gives
```
test.py:1:10: ANN401 Dynamically typed expressions (typing.Any) are disallowed
test.py:1:23: ANN401 Dynamically typed expressions (typing.Any) are disallowed
```

Could we make checking these either an option to ANN401 or we could exclude them from ANN401 and make ANN402 should someone want to disallow `Any` for these unpackings?

**Version Information**

```bash
$ flake8 --version
4.0.1 (black: 0.2.3, flake8-annotations: 2.8.0, flake8-bugbear: 22.3.23,
flake8-docstrings: 1.6.0, pydocstyle: 6.1.1, mccabe: 0.6.1, pycodestyle:
2.8.0, pyflakes: 2.4.0) CPython 3.7.13 on Darwin
```

As well as your Python version:
```bash
$ python -V
Python 3.9.12
```

**Comment by sco1** [comment]
I think this should be fairly straightforward, since the argument type is already being classified. I'll have to think about what error code approach I like best for the adjustment.
