### ISSUE TITLE
Compatibility with attrs v22.1.0

### ISSUE THREAD

**Issue by XN137** [sco1/flake8-annotations#144]
**Description**

dependabot tried upgrading `attrs` to 22.1.0 in our [repo](https://github.com/projectnessie/nessie/pull/4815) resulting in this pip install error:
```
  The conflict is caused by:
      The user requested attrs==22.1.0
      desert 2020.11.18 depends on attrs
      pytest 7.1.2 depends on attrs>=19.2.0
      pytest-mypy 0.9.1 depends on attrs>=19.0
      pytest-recording 0.12.1 depends on attrs
      flake8-annotations 2.9.0 depends on attrs<22.0 and >=21.4
```

**Rationale/Use Case**
If there are no strong reasons to version cap the `attrs` dependency maybe it could be less strict or at least support 22.1.x for the time being.
Thank you.

**Comment by sco1** [comment]
That can probably be relaxed without any issues, I'll try to take a look at it this afternoon.

**Comment by XN137** [comment]
Just wanted to confirm that the problem is indeed resolved when combining the 2 new versions.
Thank you for the quick response.
