### ISSUE TITLE
Syntax error when type in commented out code

### ISSUE THREAD

**Issue by sco1** [sco1/flake8-annotations#151]
ran into this on valid, commented-out  code using PEP 526 type hints - providing here as an example:

```python
# class A():
#     type: str

pass
```

results in:

```
foo.py: "flake8-annotations[ANN]" failed during execution due to SyntaxError('invalid syntax', ('<unknown>', 2, 13, '#     type: str\n', 2, 16))
Run flake8 with greater verbosity to see more details
0
```

_Originally posted by @mbrancato in https://github.com/sco1/flake8-annotations/issues/95#issuecomment-1380348699_

**Comment by sco1** [comment]
Interesting, expanding on the details it seems to be coming from `ast`, which seems strange since it is technically valid Python:

```py
import ast

src = """\
# class A():
#     type: str
"""

tree = ast.parse(src, type_comments=True)
```

```py
Traceback (most recent call last):
  File "~\asdf.py", line 8, in <module>
    tree = ast.parse(src, type_comments=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\Lib\ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 2
    #     type: str
                ^^^
SyntaxError: invalid syntax
```

If this is a trivial fix then I'll try to get it included, otherwise I'm hesitant to go too in-depth with supporting type comments just to drop them in a few months.

**Comment by mbrancato** [comment]
I understand. I saw they are being dropped in v3.
