### ISSUE TITLE
ANN402 not working?

### ISSUE THREAD

**Issue by sziem** [sco1/flake8-annotations#154]
**Describe the bug**
I wanted to try out the new ANN402 error code to figure out, whether it would also be triggered by `type: ignore` comments.  So I added the line `extend-select = ANN402` to my setup.cfg and ran the code below. 

I was expecting to definetly get a linter error in line 4, and possibly in line 1, but I didn't get any.  Did I misunderstand this feature or is this a bug?

**To Reproduce**
Minimal code example to reproduce the behavior:

```bash
$ flake8 src
```

```py
# src/foo.py
import datetime  # type: ignore[import]

def f() -> None:
    dt = datetime.datetime.now()  # type: datetime.datetime
    print(dt)
```

**Version Information**
Please provide the full output of `flake8 --version`

```bash
$ flake8 --version
6.0.0 (darglint: 1.8.1, flake8-annotations: 3.0.0, flake8-black: 0.3.6, flake8-bugbear: 23.3.23, flake8-cognitive-complexity: 0.1.0, flake8-comprehensions: 3.11.1, flake8-debugger: 4.1.2, flake8-docstrings: 1.7.0, flake8-formatter-junit-xml: 0.0.6, flake8-isort: 6.0.0, flake8-mutable: 1.2.0,
flake8-simplify: 0.19.3, flake8-super: 0.1.3, mccabe: 0.7.0, pep8-naming: 0.13.3, pycodestyle: 2.10.0, pyflakes: 3.0.1) CPython 3.8.16 on Linux
```

As well as your Python version:
```bash
$ python -V
Python 3.8.16
```

**Comment by sco1** [comment]
This is as intended, but could probably be better clarified in the README. Only function declarations are checked by this plugin, so function/module bodies are not considered.

There may be another linting plugin that does check the entire source but I'm personally not familiar with one. If you're a pre-commit user, the [pygrep hooks](https://github.com/pre-commit/pygrep-hooks) contain a `python-use-type-annotations` hook that can enforce this.
