### ISSUE TITLE
`ANN101` enhancement

### ISSUE THREAD

**Issue by Danipulok** [sco1/flake8-annotations#162]
Hi here! I have been using your package for a while now. Thanks for it.
And this whole time I was suppressing `ANN101`, because IMO it 'bugged' with self and cls.
Is it expected to be like this? It seems so, but why?

**Description**
Why does `ANN101` requires annotations for self and cls in methods / classmethod?
All the modern and even old checkers and IDE know what's passed to self/cls.
Why add unnecessary code that will be changed depending on class name (`Self` is not that much supported IMO)?

**Rationale/Use Case**
```python
class A:
    def foo(self) -> None:
        pass

    @classmethod
    def bar(cls) -> None:
        pass
```

```flake8
mre.py:2:13: ANN101 Missing type annotation for self in method
mre.py:6:13: ANN102 Missing type annotation for cls in classmethod
```

I propose to change this rule behavior for first argument in methods / classmethods and do not require it in these cases.
What do you think?

**Comment by sco1** [comment]
See: #75
